'use client';

import React, { useState, useCallback } from 'react';

// Define types for different kinds of generated assets
interface GeneratedImage {
  type: 'image';
  url: string;
  alt: string;
}

interface GeneratedText {
  type: 'text';
  content: string;
  title?: string;
}

interface GeneratedCard {
  type: 'card';
  title: string;
  description: string;
  imageUrl?: string;
  ctaText?: string;
  backgroundColor?: string;
  textColor?: string;
  styleHint?: string; // To reflect the style customization
}

type GeneratedAsset = GeneratedImage | GeneratedText | GeneratedCard;

// Mock AI generation function to simulate backend API call
const mockGenerateAIAsset = async (
  prompt: string,
  assetType: 'image' | 'text' | 'card',
  customizations?: Record<string, any>
): Promise<GeneratedAsset> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      if (assetType === 'image') {
        resolve({
          type: 'image',
          url: `https://picsum.photos/seed/${Math.random()}/800/450`, // Random image
          alt: `AI generated image for: ${prompt}`,
        });
      } else if (assetType === 'text') {
        resolve({
          type: 'text',
          title: `AI-Generated Title: ${prompt.substring(0, 50)}${prompt.length > 50 ? '...' : ''}`,
          content: `This is a placeholder for AI-generated text based on your prompt: "${prompt}". It's designed to be engaging and relevant to your article. ${customizations?.tone ? `(Tone: ${customizations.tone})` : ''}\n\nFurther details and expansion would be provided by a real AI model, focusing on clarity and impact.`,
        });
      } else if (assetType === 'card') {
        resolve({
          type: 'card',
          title: `AI Card: ${prompt.substring(0, 30)}${prompt.length > 30 ? '...' : ''}`,
          description: `A compelling description for your article card, generated by AI, reflecting the prompt and chosen style. ${customizations?.style ? `(Style: ${customizations.style})` : ''}`,
          imageUrl: `https://picsum.photos/seed/${Math.random()}/400/200`, // Random image for card
          ctaText: customizations?.cta || 'Read More',
          backgroundColor: customizations?.bgColor || '#f0f4f8',
          textColor: customizations?.txtColor || '#1a202c',
          styleHint: customizations?.style || 'modern',
        });
      }
    }, 1500); // Simulate network delay
  });
};

const ForgePage: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('');
  const [assetType, setAssetType] = useState<'image' | 'text' | 'card'>('image');
  const [generatedAsset, setGeneratedAsset] = useState<GeneratedAsset | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  // Customization states for Card Customizer
  const [cardCta, setCardCta] = useState<string>('Read More');
  const [cardBgColor, setCardBgColor] = useState<string>('#f0f4f8');
  const [cardTxtColor, setCardTxtColor] = useState<string>('#1a202c');
  const [cardStyle, setCardStyle] = useState<string>('modern'); // e.g., 'modern', 'classic', 'minimal'

  const handleGenerate = useCallback(async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt to generate an asset.');
      return;
    }

    setIsLoading(true);
    setError(null);
    setGeneratedAsset(null); // Clear previous asset

    try {
      const customizations: Record<string, any> = {};
      if (assetType === 'card') {
        customizations.cta = cardCta;
        customizations.bgColor = cardBgColor;
        customizations.txtColor = cardTxtColor;
        customizations.style = cardStyle;
      }
      // Future: Add customizations for 'image' (e.g., aspect ratio, style) or 'text' (e.g., tone, length)

      const asset = await mockGenerateAIAsset(prompt, assetType, customizations);
      setGeneratedAsset(asset);
    } catch (err) {
      setError('Failed to generate asset. Please check your prompt and try again.');
      console.error('AI generation error:', err);
    } finally {
      setIsLoading(false);
    }
  }, [prompt, assetType, cardCta, cardBgColor, cardTxtColor, cardStyle]);

  // Renders the appropriate UI for the generated asset based on its type
  const renderGeneratedAsset = () => {
    if (!generatedAsset) return null;

    switch (generatedAsset.type) {
      case 'image':
        return (
          <div className="p-4 border border-gray-300 rounded-lg bg-white shadow-sm">
            <h3 className="text-lg font-semibold mb-2">Generated Image (Ad Studio)</h3>
            <img src={generatedAsset.url} alt={generatedAsset.alt} className="max-w-full h-auto rounded-md object-cover" />
            <p className="text-sm text-gray-600 mt-2">Alt Text: {generatedAsset.alt}</p>
          </div>
        );
      case 'text':
        return (
          <div className="p-4 border border-gray-300 rounded-lg bg-white shadow-sm">
            <h3 className="text-lg font-semibold mb-2">{generatedAsset.title || 'Generated Text (Ad Studio)'}</h3>
            <p className="text-gray-700 whitespace-pre-wrap">{generatedAsset.content}</p>
          </div>
        );
      case 'card':
        return (
          <div
            className="p-6 rounded-lg shadow-lg flex flex-col items-start transition-all duration-300 ease-in-out"
            style={{ backgroundColor: generatedAsset.backgroundColor, color: generatedAsset.textColor }}
          >
            <h3 className="text-xl font-bold mb-2">{generatedAsset.title}</h3>
            {generatedAsset.imageUrl && (
              <img src={generatedAsset.imageUrl} alt={generatedAsset.title} className="w-full h-48 object-cover rounded-md mb-4" />
            )}
            <p className="text-base mb-4 flex-grow">{generatedAsset.description}</p>
            {generatedAsset.ctaText && (
              <button
                className="px-5 py-2 rounded-full font-semibold text-sm mt-auto"
                style={{ backgroundColor: generatedAsset.textColor, color: generatedAsset.backgroundColor }}
              >
                {generatedAsset.ctaText}
              </button>
            )}
            <p className="text-xs mt-4 opacity-70">Style: {generatedAsset.styleHint}</p>
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 p-8">
      <h1 className="text-4xl font-extrabold text-gray-900 mb-8">
        Forge: AI Asset Generator <span className="text-blue-600">for Architects</span>
      </h1>
      <p className="text-lg text-gray-700 mb-10 max-w-3xl">
        Unleash the power of generative AI to create stunning assets for your articles, marketing campaigns, and UI components.
        From "Ad Studio" content to "Card Customizer" designs, bring your vision to life instantly.
      </p>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Input and Controls Section */}
        <div className="lg:col-span-1 bg-white p-6 rounded-xl shadow-lg h-fit sticky top-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-6">Generate New Asset</h2>

          <div className="mb-6">
            <label htmlFor="prompt" className="block text-sm font-medium text-gray-700 mb-2">
              AI Prompt
            </label>
            <textarea
              id="prompt"
              className="w-full p-3 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 resize-y min-h-[100px]"
              placeholder="Describe the asset you want to create (e.g., 'A vibrant image of a futuristic city at sunset', 'A catchy headline for an article about AI in banking', 'A blog card for a post on open banking APIs')"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={5}
            ></textarea>
          </div>

          <div className="mb-6">
            <label htmlFor="assetType" className="block text-sm font-medium text-gray-700 mb-2">
              Asset Type
            </label>
            <select
              id="assetType"
              className="w-full p-3 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 bg-white"
              value={assetType}
              onChange={(e) => {
                setAssetType(e.target.value as 'image' | 'text' | 'card');
                setGeneratedAsset(null); // Clear previous asset when type changes
              }}
            >
              <option value="image">Article Image (Ad Studio)</option>
              <option value="text">Article Text/Copy (Ad Studio)</option>
              <option value="card">Blog/Article Card (Card Customizer)</option>
            </select>
          </div>

          {assetType === 'card' && (
            <div className="mb-6 p-4 border border-blue-200 bg-blue-50 rounded-lg">
              <h3 className="text-lg font-semibold text-blue-800 mb-4">Card Customizer Options</h3>
              <div className="mb-4">
                <label htmlFor="cardCta" className="block text-sm font-medium text-gray-700 mb-2">
                  Call to Action Text
                </label>
                <input
                  type="text"
                  id="cardCta"
                  className="w-full p-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500"
                  value={cardCta}
                  onChange={(e) => setCardCta(e.target.value)}
                  placeholder="e.g., Learn More, Discover Now"
                />
              </div>
              <div className="mb-4">
                <label htmlFor="cardBgColor" className="block text-sm font-medium text-gray-700 mb-2">
                  Background Color
                </label>
                <input
                  type="color"
                  id="cardBgColor"
                  className="w-full h-10 p-1 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500"
                  value={cardBgColor}
                  onChange={(e) => setCardBgColor(e.target.value)}
                />
              </div>
              <div className="mb-4">
                <label htmlFor="cardTxtColor" className="block text-sm font-medium text-gray-700 mb-2">
                  Text Color
                </label>
                <input
                  type="color"
                  id="cardTxtColor"
                  className="w-full h-10 p-1 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500"
                  value={cardTxtColor}
                  onChange={(e) => setCardTxtColor(e.target.value)}
                />
              </div>
              <div className="mb-4">
                <label htmlFor="cardStyle" className="block text-sm font-medium text-gray-700 mb-2">
                  Card Style Hint
                </label>
                <select
                  id="cardStyle"
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 bg-white"
                  value={cardStyle}
                  onChange={(e) => setCardStyle(e.target.value)}
                >
                  <option value="modern">Modern</option>
                  <option value="classic">Classic</option>
                  <option value="minimal">Minimalist</option>
                  <option value="bold">Bold</option>
                  <option value="elegant">Elegant</option>
                </select>
              </div>
            </div>
          )}

          <button
            onClick={handleGenerate}
            className="w-full bg-blue-600 text-white py-3 px-4 rounded-lg font-semibold hover:bg-blue-700 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Generating...
              </>
            ) : (
              'Generate Asset'
            )}
          </button>

          {error && (
            <div className="mt-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg">
              {error}
            </div>
          )}
        </div>

        {/* Output Section */}
        <div className="lg:col-span-2 bg-white p-6 rounded-xl shadow-lg">
          <h2 className="text-2xl font-bold text-gray-800 mb-6">Generated Assets</h2>

          {generatedAsset ? (
            <div className="space-y-6">
              {renderGeneratedAsset()}
            </div>
          ) : (
            <div className="p-8 text-center text-gray-500 border-2 border-dashed border-gray-300 rounded-lg">
              <p className="text-lg">Your AI-generated assets will appear here.</p>
              <p className="text-sm mt-2">Use the controls on the left to describe and create your content.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ForgePage;